baseURL = "https://oamerge.com/"
languageCode = "en-US"
title = "OA Merge"
theme = "whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Merge and share OpenAPI endpoints and schemas.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "OA Merge is a tool to help you merge and share API endpoints and OpenAPI schemas."
    meta_og_title = "OA Merge"
    meta_og_type = "website"
    meta_og_url = "https://oamerge.com"
    meta_og_image = "https://oamerge.com/favicon/android-chrome-192x192.png"
    meta_og_description = "Merge and share OpenAPI endpoints and schemas."
    meta_twitter_card = "summary"
    meta_twitter_site = "@oamerge"
    meta_twitter_creator = "@oamerge"

  [params.logo]
      mobile = "/favicon/android-chrome-192x192.png"
      standard  = "/favicon/android-chrome-192x192.png"
